
export const SET_TOKEN = 'SET_TOKEN'
export const MODAL_OPEN = "MODAL_OPEN";

export const PRODUCT_SELECTED = "PRODUCT_SELECTED";

export const PRODUCT_GET_REQUESTED = 'PRODUCT_GET_REQUESTED'
export const PRODUCT_GET_SUCCEEDED = 'PRODUCT_GET_SUCCEEDED'
export const PRODUCT_GET_FAILED = 'PRODUCT_GET_FAILED'

export const PRODUCT_ADD_REQUESTED = "PRODUCT_ADD_REQUESTED";
export const PRODUCT_ADD_SUCCEEDED = "PRODUCT_ADD_SUCCEEDED";
export const PRODUCT_ADD_FAILED = "PRODUCT_ADD_FAILED";

export const PRODUCT_UPDATE_REQUESTED = "PRODUCT_UPDATE_REQUESTED";
export const PRODUCT_UPDATE_SUCCEEDED = "PRODUCT_UPDATE_SUCCEEDED";
export const PRODUCT_UPDATE_FAILED = "PRODUCT_UPDATE_FAILED";

export const PRODUCT_DELETE_REQUESTED = "PRODUCT_DELETE_REQUESTED";
export const PRODUCT_DELETE_SUCCEEDED = "PRODUCT_DELETE_SUCCEEDED";
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED";